# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dot_product <- function(x, y) {
    .Call('_rdbb_dot_product', PACKAGE = 'rdbb', x, y)
}

performOptimization <- function(n, alpha, lambda, omega_l_eigen, sp_eigen, strike_eigen, bid_eigen, ask_eigen, pFlag_eigen) {
    .Call('_rdbb_performOptimization', PACKAGE = 'rdbb', n, alpha, lambda, omega_l_eigen, sp_eigen, strike_eigen, bid_eigen, ask_eigen, pFlag_eigen)
}

getFeasibleOptionFlags <- function(sp, bid, ask, strike, pFlag, spotsP, spbid, spask) {
    .Call('_rdbb_getFeasibleOptionFlags', PACKAGE = 'rdbb', sp, bid, ask, strike, pFlag, spotsP, spbid, spask)
}

getMidPriceQ <- function(sp, bid, ask, strike, pFlag, spotsP, spbid, spask) {
    .Call('_rdbb_getMidPriceQ', PACKAGE = 'rdbb', sp, bid, ask, strike, pFlag, spotsP, spbid, spask)
}

getMidPriceQReg <- function(sp, bid, ask, strike, pFlag, spotsP, spbid, spask) {
    .Call('_rdbb_getMidPriceQReg', PACKAGE = 'rdbb', sp, bid, ask, strike, pFlag, spotsP, spbid, spask)
}

getQReg <- function(sp, bid, ask, strike, pFlag, spotsP, spbid, spask) {
    .Call('_rdbb_getQReg', PACKAGE = 'rdbb', sp, bid, ask, strike, pFlag, spotsP, spbid, spask)
}

rcppeigen_hello_world <- function() {
    .Call('_rdbb_rcppeigen_hello_world', PACKAGE = 'rdbb')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_rdbb_rcppeigen_outerproduct', PACKAGE = 'rdbb', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_rdbb_rcppeigen_innerproduct', PACKAGE = 'rdbb', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_rdbb_rcppeigen_bothproducts', PACKAGE = 'rdbb', x)
}

